### ISSUE TITLE
illegal length of udag resp

### ISSUE THREAD

**Issue by Veralalala** [AntChainOpenLabs/AntChainBridge#11]
系统合约AuthMsg收到来自SDP的跨链消息后，emit了事件。
![image](https://github.com/AntChainOpenLab/AntChainBridgePluginSDK/assets/39075131/23145297-f859-4a63-b43e-fa6ef54e8af6)

将事件中的rawmsg放在AuthMsg的recvPkgFromRelayer中作为入参调用，报错如下：
![image](https://github.com/AntChainOpenLab/AntChainBridgePluginSDK/assets/39075131/5147cdda-92fb-479b-a2ec-0d7af2e3d497)

data：
0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000010800000014000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000193b653f636861696e3634313638393735383632393537310000000000000000ffffffff000000000000000000000000e6a9764185eae7368d08e2096ad9caf10000000000000000000000000000000000000000000000000000000000000005ffdffcefef00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a400000000000000000000000000000000074cff16d3862dea4712a0220f9202a4aa778c2500000001000000000000000000000000000000000000000000000000

**Comment by zouxyan** [comment]
[Here](https://github.com/AntChainOpenLab/AntChainBridgePluginSDK/blob/5ab01a05ac5e3936aa886a25574f83d9f01d4e75/pluginset/ethereum/offchain-plugin/src/test/java/com/alipay/antchain/bridge/plugins/ethereum/EthereumBBCServiceTest.java#L571) is the code about how to build a mocked message which can use as the input for `recvPkgFromRelayer`.
